import {
  LayoutDashboard,
  ClipboardList,
  TrendingUp,
  CalendarClock,
  Microscope,
  Boxes,
  Package,
  Headphones,
  PhoneForwarded,
  PhoneCall,
  Wrench,
  Hammer,
  Building2,
  Undo2,
  MapPin,
  Wallet,
  Coins,
  Scale,
  Smile,
  MessageCircle,
  Truck,
  Download,
  History,
  LayoutGrid,
  Settings2,
  ShieldCheck,
  Database,
  UserSearch,
  type LucideIcon,
} from "lucide-react";

export interface NavPage {
  path: string;
  label: string;
  icon: LucideIcon;
  admin?: boolean;
  active?: boolean;
}

export const NAV_PAGES: NavPage[] = [
  { path: "/", label: "KPI Overview", icon: LayoutDashboard, active: true },
  { path: "/kpis", label: "KPI Scorecard", icon: ClipboardList, active: true },
  { path: "/monthly-trends", label: "Monthly Trends", icon: TrendingUp, active: true },
  { path: "/daily-operations", label: "Daily Operations", icon: CalendarClock, active: true },
  { path: "/deep-insights", label: "Deep Insights", icon: Microscope, active: true },
  { path: "/obm-analysis", label: "OBM Analysis", icon: Boxes, active: true },
  { path: "/spare-parts", label: "Spare Parts", icon: Package, active: true },
  { path: "/call-center", label: "Call Center", icon: Headphones, active: true },
  { path: "/call-center-assignment", label: "Call Assignment", icon: PhoneForwarded, active: true },
  { path: "/call-events", label: "Call Events", icon: PhoneCall, active: true },
  { path: "/ticket-repair-history", label: "Repair History", icon: Wrench, active: true },
  { path: "/installation-analysis", label: "Installation Analysis", icon: Hammer, active: true },
  { path: "/asc-performance", label: "ASC Performance", icon: Building2, active: true },
  { path: "/rejected-returned", label: "Rejected / Returned", icon: Undo2, active: true },
  { path: "/city", label: "City Breakdown", icon: MapPin, active: true },
  { path: "/districts-map", label: "Districts Map", icon: MapPin, active: true },
  { path: "/warranty-payments", label: "Warranty Payments", icon: Wallet, active: true },
  { path: "/costs", label: "Cost Center", icon: Coins, active: true },
  { path: "/commerce-complaints", label: "Commerce Complaints", icon: Scale, active: true },
  { path: "/satisfaction", label: "Satisfaction (CSAT)", icon: Smile, active: true },
  { path: "/whatsapp", label: "WhatsApp Inbox", icon: MessageCircle, active: true },
  { path: "/shipments", label: "Shipments", icon: Truck, active: true },
  { path: "/customer-lookup", label: "Customer Lookup", icon: UserSearch, active: true },
  { path: "/export-center", label: "Export Center", icon: Download, active: true },
  { path: "/activity-log", label: "Activity Log", icon: History, active: true },
  { path: "/custom-dashboard", label: "Custom Dashboard", icon: LayoutGrid, active: true },
  { path: "/control-panel", label: "Control Panel", icon: Settings2, admin: true, active: true },
  { path: "/access", label: "Access", icon: ShieldCheck, admin: true, active: true },
  { path: "/data-editor", label: "Data Editor", icon: Database, admin: true, active: true },
];