/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PendingAnalysisRouteImport } from './routes/pending-analysis'
import { Route as ObmAnalysisRouteImport } from './routes/obm-analysis'
import { Route as MonthlyTrendsRouteImport } from './routes/monthly-trends'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as InstallationAnalysisRouteImport } from './routes/installation-analysis'
import { Route as DeepInsightsRouteImport } from './routes/deep-insights'
import { Route as DailyOperationsRouteImport } from './routes/daily-operations'
import { Route as CityRouteImport } from './routes/city'
import { Route as CallCenterRouteImport } from './routes/call-center'
import { Route as AscPerformanceRouteImport } from './routes/asc-performance'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAnalysisRoute = PendingAnalysisRouteImport.update({
  id: '/pending-analysis',
  path: '/pending-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ObmAnalysisRoute = ObmAnalysisRouteImport.update({
  id: '/obm-analysis',
  path: '/obm-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyTrendsRoute = MonthlyTrendsRouteImport.update({
  id: '/monthly-trends',
  path: '/monthly-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationAnalysisRoute = InstallationAnalysisRouteImport.update({
  id: '/installation-analysis',
  path: '/installation-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepInsightsRoute = DeepInsightsRouteImport.update({
  id: '/deep-insights',
  path: '/deep-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOperationsRoute = DailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterRoute = CallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AscPerformanceRoute = AscPerformanceRouteImport.update({
  id: '/asc-performance',
  path: '/asc-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/city': typeof CityRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/city': typeof CityRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/city': typeof CityRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asc-performance'
    | '/call-center'
    | '/city'
    | '/daily-operations'
    | '/deep-insights'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asc-performance'
    | '/call-center'
    | '/city'
    | '/daily-operations'
    | '/deep-insights'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/asc-performance'
    | '/call-center'
    | '/city'
    | '/daily-operations'
    | '/deep-insights'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscPerformanceRoute: typeof AscPerformanceRoute
  CallCenterRoute: typeof CallCenterRoute
  CityRoute: typeof CityRoute
  DailyOperationsRoute: typeof DailyOperationsRoute
  DeepInsightsRoute: typeof DeepInsightsRoute
  InstallationAnalysisRoute: typeof InstallationAnalysisRoute
  KpisRoute: typeof KpisRoute
  MonthlyTrendsRoute: typeof MonthlyTrendsRoute
  ObmAnalysisRoute: typeof ObmAnalysisRoute
  PendingAnalysisRoute: typeof PendingAnalysisRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-analysis': {
      id: '/pending-analysis'
      path: '/pending-analysis'
      fullPath: '/pending-analysis'
      preLoaderRoute: typeof PendingAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obm-analysis': {
      id: '/obm-analysis'
      path: '/obm-analysis'
      fullPath: '/obm-analysis'
      preLoaderRoute: typeof ObmAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-trends': {
      id: '/monthly-trends'
      path: '/monthly-trends'
      fullPath: '/monthly-trends'
      preLoaderRoute: typeof MonthlyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation-analysis': {
      id: '/installation-analysis'
      path: '/installation-analysis'
      fullPath: '/installation-analysis'
      preLoaderRoute: typeof InstallationAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-insights': {
      id: '/deep-insights'
      path: '/deep-insights'
      fullPath: '/deep-insights'
      preLoaderRoute: typeof DeepInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-operations': {
      id: '/daily-operations'
      path: '/daily-operations'
      fullPath: '/daily-operations'
      preLoaderRoute: typeof DailyOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center': {
      id: '/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof CallCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asc-performance': {
      id: '/asc-performance'
      path: '/asc-performance'
      fullPath: '/asc-performance'
      preLoaderRoute: typeof AscPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscPerformanceRoute: AscPerformanceRoute,
  CallCenterRoute: CallCenterRoute,
  CityRoute: CityRoute,
  DailyOperationsRoute: DailyOperationsRoute,
  DeepInsightsRoute: DeepInsightsRoute,
  InstallationAnalysisRoute: InstallationAnalysisRoute,
  KpisRoute: KpisRoute,
  MonthlyTrendsRoute: MonthlyTrendsRoute,
  ObmAnalysisRoute: ObmAnalysisRoute,
  PendingAnalysisRoute: PendingAnalysisRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
