/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WarrantyPaymentsRouteImport } from './routes/warranty-payments'
import { Route as TicketRepairHistoryRouteImport } from './routes/ticket-repair-history'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SatisfactionRouteImport } from './routes/satisfaction'
import { Route as RejectedReturnedRouteImport } from './routes/rejected-returned'
import { Route as PendingAnalysisRouteImport } from './routes/pending-analysis'
import { Route as ObmAnalysisRouteImport } from './routes/obm-analysis'
import { Route as MonthlyTrendsRouteImport } from './routes/monthly-trends'
import { Route as KpisRouteImport } from './routes/kpis'
import { Route as InstallationAnalysisRouteImport } from './routes/installation-analysis'
import { Route as ExportCenterRouteImport } from './routes/export-center'
import { Route as DistrictsMapRouteImport } from './routes/districts-map'
import { Route as DeepInsightsRouteImport } from './routes/deep-insights'
import { Route as DataEditorRouteImport } from './routes/data-editor'
import { Route as DailyOperationsRouteImport } from './routes/daily-operations'
import { Route as CustomerLookupRouteImport } from './routes/customer-lookup'
import { Route as CustomDashboardRouteImport } from './routes/custom-dashboard'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as ControlPanelRouteImport } from './routes/control-panel'
import { Route as CommerceComplaintsRouteImport } from './routes/commerce-complaints'
import { Route as CityRouteImport } from './routes/city'
import { Route as CallEventsRouteImport } from './routes/call-events'
import { Route as CallCenterAssignmentRouteImport } from './routes/call-center-assignment'
import { Route as CallCenterRouteImport } from './routes/call-center'
import { Route as AscPerformanceRouteImport } from './routes/asc-performance'
import { Route as ActivityLogRouteImport } from './routes/activity-log'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSheetWriteRouteImport } from './routes/api/public/sheet-write'
import { Route as ApiPublicSheetReadRouteImport } from './routes/api/public/sheet-read'
import { Route as ApiPublicAccessWriteRouteImport } from './routes/api/public/access-write'
import { Route as ApiPublicAccessCheckRouteImport } from './routes/api/public/access-check'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyPaymentsRoute = WarrantyPaymentsRouteImport.update({
  id: '/warranty-payments',
  path: '/warranty-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRepairHistoryRoute = TicketRepairHistoryRouteImport.update({
  id: '/ticket-repair-history',
  path: '/ticket-repair-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisfactionRoute = SatisfactionRouteImport.update({
  id: '/satisfaction',
  path: '/satisfaction',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedReturnedRoute = RejectedReturnedRouteImport.update({
  id: '/rejected-returned',
  path: '/rejected-returned',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAnalysisRoute = PendingAnalysisRouteImport.update({
  id: '/pending-analysis',
  path: '/pending-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ObmAnalysisRoute = ObmAnalysisRouteImport.update({
  id: '/obm-analysis',
  path: '/obm-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyTrendsRoute = MonthlyTrendsRouteImport.update({
  id: '/monthly-trends',
  path: '/monthly-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const KpisRoute = KpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationAnalysisRoute = InstallationAnalysisRouteImport.update({
  id: '/installation-analysis',
  path: '/installation-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportCenterRoute = ExportCenterRouteImport.update({
  id: '/export-center',
  path: '/export-center',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsMapRoute = DistrictsMapRouteImport.update({
  id: '/districts-map',
  path: '/districts-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepInsightsRoute = DeepInsightsRouteImport.update({
  id: '/deep-insights',
  path: '/deep-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEditorRoute = DataEditorRouteImport.update({
  id: '/data-editor',
  path: '/data-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOperationsRoute = DailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLookupRoute = CustomerLookupRouteImport.update({
  id: '/customer-lookup',
  path: '/customer-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDashboardRoute = CustomDashboardRouteImport.update({
  id: '/custom-dashboard',
  path: '/custom-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelRoute = ControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceComplaintsRoute = CommerceComplaintsRouteImport.update({
  id: '/commerce-complaints',
  path: '/commerce-complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const CallEventsRoute = CallEventsRouteImport.update({
  id: '/call-events',
  path: '/call-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterAssignmentRoute = CallCenterAssignmentRouteImport.update({
  id: '/call-center-assignment',
  path: '/call-center-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCenterRoute = CallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AscPerformanceRoute = AscPerformanceRouteImport.update({
  id: '/asc-performance',
  path: '/asc-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogRoute = ActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetWriteRoute = ApiPublicSheetWriteRouteImport.update({
  id: '/api/public/sheet-write',
  path: '/api/public/sheet-write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetReadRoute = ApiPublicSheetReadRouteImport.update({
  id: '/api/public/sheet-read',
  path: '/api/public/sheet-read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccessWriteRoute = ApiPublicAccessWriteRouteImport.update({
  id: '/api/public/access-write',
  path: '/api/public/access-write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAccessCheckRoute = ApiPublicAccessCheckRouteImport.update({
  id: '/api/public/access-check',
  path: '/api/public/access-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activity-log': typeof ActivityLogRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-assignment': typeof CallCenterAssignmentRoute
  '/call-events': typeof CallEventsRoute
  '/city': typeof CityRoute
  '/commerce-complaints': typeof CommerceComplaintsRoute
  '/control-panel': typeof ControlPanelRoute
  '/costs': typeof CostsRoute
  '/custom-dashboard': typeof CustomDashboardRoute
  '/customer-lookup': typeof CustomerLookupRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/data-editor': typeof DataEditorRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/districts-map': typeof DistrictsMapRoute
  '/export-center': typeof ExportCenterRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/rejected-returned': typeof RejectedReturnedRoute
  '/satisfaction': typeof SatisfactionRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
  '/ticket-repair-history': typeof TicketRepairHistoryRoute
  '/warranty-payments': typeof WarrantyPaymentsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/public/access-check': typeof ApiPublicAccessCheckRoute
  '/api/public/access-write': typeof ApiPublicAccessWriteRoute
  '/api/public/sheet-read': typeof ApiPublicSheetReadRoute
  '/api/public/sheet-write': typeof ApiPublicSheetWriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activity-log': typeof ActivityLogRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-assignment': typeof CallCenterAssignmentRoute
  '/call-events': typeof CallEventsRoute
  '/city': typeof CityRoute
  '/commerce-complaints': typeof CommerceComplaintsRoute
  '/control-panel': typeof ControlPanelRoute
  '/costs': typeof CostsRoute
  '/custom-dashboard': typeof CustomDashboardRoute
  '/customer-lookup': typeof CustomerLookupRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/data-editor': typeof DataEditorRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/districts-map': typeof DistrictsMapRoute
  '/export-center': typeof ExportCenterRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/rejected-returned': typeof RejectedReturnedRoute
  '/satisfaction': typeof SatisfactionRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
  '/ticket-repair-history': typeof TicketRepairHistoryRoute
  '/warranty-payments': typeof WarrantyPaymentsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/public/access-check': typeof ApiPublicAccessCheckRoute
  '/api/public/access-write': typeof ApiPublicAccessWriteRoute
  '/api/public/sheet-read': typeof ApiPublicSheetReadRoute
  '/api/public/sheet-write': typeof ApiPublicSheetWriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/activity-log': typeof ActivityLogRoute
  '/asc-performance': typeof AscPerformanceRoute
  '/call-center': typeof CallCenterRoute
  '/call-center-assignment': typeof CallCenterAssignmentRoute
  '/call-events': typeof CallEventsRoute
  '/city': typeof CityRoute
  '/commerce-complaints': typeof CommerceComplaintsRoute
  '/control-panel': typeof ControlPanelRoute
  '/costs': typeof CostsRoute
  '/custom-dashboard': typeof CustomDashboardRoute
  '/customer-lookup': typeof CustomerLookupRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/data-editor': typeof DataEditorRoute
  '/deep-insights': typeof DeepInsightsRoute
  '/districts-map': typeof DistrictsMapRoute
  '/export-center': typeof ExportCenterRoute
  '/installation-analysis': typeof InstallationAnalysisRoute
  '/kpis': typeof KpisRoute
  '/monthly-trends': typeof MonthlyTrendsRoute
  '/obm-analysis': typeof ObmAnalysisRoute
  '/pending-analysis': typeof PendingAnalysisRoute
  '/rejected-returned': typeof RejectedReturnedRoute
  '/satisfaction': typeof SatisfactionRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spare-parts': typeof SparePartsRoute
  '/ticket-repair-history': typeof TicketRepairHistoryRoute
  '/warranty-payments': typeof WarrantyPaymentsRoute
  '/whatsapp': typeof WhatsappRoute
  '/api/public/access-check': typeof ApiPublicAccessCheckRoute
  '/api/public/access-write': typeof ApiPublicAccessWriteRoute
  '/api/public/sheet-read': typeof ApiPublicSheetReadRoute
  '/api/public/sheet-write': typeof ApiPublicSheetWriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/activity-log'
    | '/asc-performance'
    | '/call-center'
    | '/call-center-assignment'
    | '/call-events'
    | '/city'
    | '/commerce-complaints'
    | '/control-panel'
    | '/costs'
    | '/custom-dashboard'
    | '/customer-lookup'
    | '/daily-operations'
    | '/data-editor'
    | '/deep-insights'
    | '/districts-map'
    | '/export-center'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/rejected-returned'
    | '/satisfaction'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
    | '/ticket-repair-history'
    | '/warranty-payments'
    | '/whatsapp'
    | '/api/public/access-check'
    | '/api/public/access-write'
    | '/api/public/sheet-read'
    | '/api/public/sheet-write'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/activity-log'
    | '/asc-performance'
    | '/call-center'
    | '/call-center-assignment'
    | '/call-events'
    | '/city'
    | '/commerce-complaints'
    | '/control-panel'
    | '/costs'
    | '/custom-dashboard'
    | '/customer-lookup'
    | '/daily-operations'
    | '/data-editor'
    | '/deep-insights'
    | '/districts-map'
    | '/export-center'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/rejected-returned'
    | '/satisfaction'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
    | '/ticket-repair-history'
    | '/warranty-payments'
    | '/whatsapp'
    | '/api/public/access-check'
    | '/api/public/access-write'
    | '/api/public/sheet-read'
    | '/api/public/sheet-write'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/activity-log'
    | '/asc-performance'
    | '/call-center'
    | '/call-center-assignment'
    | '/call-events'
    | '/city'
    | '/commerce-complaints'
    | '/control-panel'
    | '/costs'
    | '/custom-dashboard'
    | '/customer-lookup'
    | '/daily-operations'
    | '/data-editor'
    | '/deep-insights'
    | '/districts-map'
    | '/export-center'
    | '/installation-analysis'
    | '/kpis'
    | '/monthly-trends'
    | '/obm-analysis'
    | '/pending-analysis'
    | '/rejected-returned'
    | '/satisfaction'
    | '/shipments'
    | '/sitemap.xml'
    | '/spare-parts'
    | '/ticket-repair-history'
    | '/warranty-payments'
    | '/whatsapp'
    | '/api/public/access-check'
    | '/api/public/access-write'
    | '/api/public/sheet-read'
    | '/api/public/sheet-write'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  ActivityLogRoute: typeof ActivityLogRoute
  AscPerformanceRoute: typeof AscPerformanceRoute
  CallCenterRoute: typeof CallCenterRoute
  CallCenterAssignmentRoute: typeof CallCenterAssignmentRoute
  CallEventsRoute: typeof CallEventsRoute
  CityRoute: typeof CityRoute
  CommerceComplaintsRoute: typeof CommerceComplaintsRoute
  ControlPanelRoute: typeof ControlPanelRoute
  CostsRoute: typeof CostsRoute
  CustomDashboardRoute: typeof CustomDashboardRoute
  CustomerLookupRoute: typeof CustomerLookupRoute
  DailyOperationsRoute: typeof DailyOperationsRoute
  DataEditorRoute: typeof DataEditorRoute
  DeepInsightsRoute: typeof DeepInsightsRoute
  DistrictsMapRoute: typeof DistrictsMapRoute
  ExportCenterRoute: typeof ExportCenterRoute
  InstallationAnalysisRoute: typeof InstallationAnalysisRoute
  KpisRoute: typeof KpisRoute
  MonthlyTrendsRoute: typeof MonthlyTrendsRoute
  ObmAnalysisRoute: typeof ObmAnalysisRoute
  PendingAnalysisRoute: typeof PendingAnalysisRoute
  RejectedReturnedRoute: typeof RejectedReturnedRoute
  SatisfactionRoute: typeof SatisfactionRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SparePartsRoute: typeof SparePartsRoute
  TicketRepairHistoryRoute: typeof TicketRepairHistoryRoute
  WarrantyPaymentsRoute: typeof WarrantyPaymentsRoute
  WhatsappRoute: typeof WhatsappRoute
  ApiPublicAccessCheckRoute: typeof ApiPublicAccessCheckRoute
  ApiPublicAccessWriteRoute: typeof ApiPublicAccessWriteRoute
  ApiPublicSheetReadRoute: typeof ApiPublicSheetReadRoute
  ApiPublicSheetWriteRoute: typeof ApiPublicSheetWriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty-payments': {
      id: '/warranty-payments'
      path: '/warranty-payments'
      fullPath: '/warranty-payments'
      preLoaderRoute: typeof WarrantyPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-repair-history': {
      id: '/ticket-repair-history'
      path: '/ticket-repair-history'
      fullPath: '/ticket-repair-history'
      preLoaderRoute: typeof TicketRepairHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satisfaction': {
      id: '/satisfaction'
      path: '/satisfaction'
      fullPath: '/satisfaction'
      preLoaderRoute: typeof SatisfactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected-returned': {
      id: '/rejected-returned'
      path: '/rejected-returned'
      fullPath: '/rejected-returned'
      preLoaderRoute: typeof RejectedReturnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-analysis': {
      id: '/pending-analysis'
      path: '/pending-analysis'
      fullPath: '/pending-analysis'
      preLoaderRoute: typeof PendingAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obm-analysis': {
      id: '/obm-analysis'
      path: '/obm-analysis'
      fullPath: '/obm-analysis'
      preLoaderRoute: typeof ObmAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-trends': {
      id: '/monthly-trends'
      path: '/monthly-trends'
      fullPath: '/monthly-trends'
      preLoaderRoute: typeof MonthlyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpis': {
      id: '/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof KpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation-analysis': {
      id: '/installation-analysis'
      path: '/installation-analysis'
      fullPath: '/installation-analysis'
      preLoaderRoute: typeof InstallationAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-center': {
      id: '/export-center'
      path: '/export-center'
      fullPath: '/export-center'
      preLoaderRoute: typeof ExportCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts-map': {
      id: '/districts-map'
      path: '/districts-map'
      fullPath: '/districts-map'
      preLoaderRoute: typeof DistrictsMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-insights': {
      id: '/deep-insights'
      path: '/deep-insights'
      fullPath: '/deep-insights'
      preLoaderRoute: typeof DeepInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-editor': {
      id: '/data-editor'
      path: '/data-editor'
      fullPath: '/data-editor'
      preLoaderRoute: typeof DataEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-operations': {
      id: '/daily-operations'
      path: '/daily-operations'
      fullPath: '/daily-operations'
      preLoaderRoute: typeof DailyOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-lookup': {
      id: '/customer-lookup'
      path: '/customer-lookup'
      fullPath: '/customer-lookup'
      preLoaderRoute: typeof CustomerLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-dashboard': {
      id: '/custom-dashboard'
      path: '/custom-dashboard'
      fullPath: '/custom-dashboard'
      preLoaderRoute: typeof CustomDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel': {
      id: '/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof ControlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce-complaints': {
      id: '/commerce-complaints'
      path: '/commerce-complaints'
      fullPath: '/commerce-complaints'
      preLoaderRoute: typeof CommerceComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-events': {
      id: '/call-events'
      path: '/call-events'
      fullPath: '/call-events'
      preLoaderRoute: typeof CallEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center-assignment': {
      id: '/call-center-assignment'
      path: '/call-center-assignment'
      fullPath: '/call-center-assignment'
      preLoaderRoute: typeof CallCenterAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-center': {
      id: '/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof CallCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asc-performance': {
      id: '/asc-performance'
      path: '/asc-performance'
      fullPath: '/asc-performance'
      preLoaderRoute: typeof AscPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log': {
      id: '/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof ActivityLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheet-write': {
      id: '/api/public/sheet-write'
      path: '/api/public/sheet-write'
      fullPath: '/api/public/sheet-write'
      preLoaderRoute: typeof ApiPublicSheetWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheet-read': {
      id: '/api/public/sheet-read'
      path: '/api/public/sheet-read'
      fullPath: '/api/public/sheet-read'
      preLoaderRoute: typeof ApiPublicSheetReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/access-write': {
      id: '/api/public/access-write'
      path: '/api/public/access-write'
      fullPath: '/api/public/access-write'
      preLoaderRoute: typeof ApiPublicAccessWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/access-check': {
      id: '/api/public/access-check'
      path: '/api/public/access-check'
      fullPath: '/api/public/access-check'
      preLoaderRoute: typeof ApiPublicAccessCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  ActivityLogRoute: ActivityLogRoute,
  AscPerformanceRoute: AscPerformanceRoute,
  CallCenterRoute: CallCenterRoute,
  CallCenterAssignmentRoute: CallCenterAssignmentRoute,
  CallEventsRoute: CallEventsRoute,
  CityRoute: CityRoute,
  CommerceComplaintsRoute: CommerceComplaintsRoute,
  ControlPanelRoute: ControlPanelRoute,
  CostsRoute: CostsRoute,
  CustomDashboardRoute: CustomDashboardRoute,
  CustomerLookupRoute: CustomerLookupRoute,
  DailyOperationsRoute: DailyOperationsRoute,
  DataEditorRoute: DataEditorRoute,
  DeepInsightsRoute: DeepInsightsRoute,
  DistrictsMapRoute: DistrictsMapRoute,
  ExportCenterRoute: ExportCenterRoute,
  InstallationAnalysisRoute: InstallationAnalysisRoute,
  KpisRoute: KpisRoute,
  MonthlyTrendsRoute: MonthlyTrendsRoute,
  ObmAnalysisRoute: ObmAnalysisRoute,
  PendingAnalysisRoute: PendingAnalysisRoute,
  RejectedReturnedRoute: RejectedReturnedRoute,
  SatisfactionRoute: SatisfactionRoute,
  ShipmentsRoute: ShipmentsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SparePartsRoute: SparePartsRoute,
  TicketRepairHistoryRoute: TicketRepairHistoryRoute,
  WarrantyPaymentsRoute: WarrantyPaymentsRoute,
  WhatsappRoute: WhatsappRoute,
  ApiPublicAccessCheckRoute: ApiPublicAccessCheckRoute,
  ApiPublicAccessWriteRoute: ApiPublicAccessWriteRoute,
  ApiPublicSheetReadRoute: ApiPublicSheetReadRoute,
  ApiPublicSheetWriteRoute: ApiPublicSheetWriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
